import Head from 'next/head'
import { Banner } from '../components/Banner'
import { NavBar } from '../components/Navbar/index'
import { About } from '../components/About'
import { Flex , Stack} from '@chakra-ui/react'
import { Art } from '../components/ArtGallery/ArtGallery'
import { Roadmap } from '../components/Roadmap'
import { Footer } from '../components/Footer'
import { FAQ } from '../components/FAQ'
import { Card } from '../components/Card'
import { CreateNFT } from '../components/CreateNFT'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex  direction='column' justify='center' align='center' bg='primary' mx='auto' w='100%' position='relative'  >
        <Stack spacing={{sm:"40%",md:"30%",lg:"20%",xl:'15%'}}  w='100%' position='relative'>
            <NavBar /> 
            <Banner />
            {/* <About /> */}
            {/* <Card/> */}
            {/* <Art />  */}
            {/* <Roadmap /> */}
            {/* <CreateNFT/>  */}
            {/* <FAQ />  */}
            {/* <Footer />   */}
          </Stack>
      </Flex>
      
    </div>
  )
}
