import Head from 'next/head'
import { Banner } from '../components/Banner'
import { NavBar } from '../components/Navbar/index'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Banner/>
    </div>
  )
}
